export const classSkills =  {
    "Jedi" : [{"name" : "Acrobatics", "ability" : "(Dex)"},{"name" : "Endurance", "ability" : "(Con)"}, {"name" : "Initiative", "ability" : "(Dex)"}, {"name" : "Jump", "ability" : "(Str)"}, {"name" : "Knowledge (Bureaucracy)", "ability" : "(Int)"}, {"name" : "Knowledge (Galactic Lore)", "ability" : "(Int)"},{"name" : "Knowledge (Life Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Physical Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Social Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Tactics)", "ability" : "(Int)"},{"name" : "Knowledge (Technology)", "ability" : "(Int)"},{"name" : "Mechanics", "ability" : "(Int)"},{"name" : "Perception", "ability" : "(Wis)"} ,{"name" : "Pilot", "ability" : "(Dex)"} ,{"name" : "Use the Force", "ability" : "(Cha)"} 
  ],
    "Noble" : [{"name" : "Deception", "ability" : "(Cha)"},{"name" : "Gather Information", "ability" : "(Cha)"},{"name" : "Initiative", "ability" : "(Dex)"} ,{"name" : "Knowledge (Bureaucracy)", "ability" : "(Int)"}, {"name" : "Knowledge (Galactic Lore)", "ability" : "(Int)"},{"name" : "Knowledge (Life Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Physical Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Social Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Tactics)", "ability" : "(Int)"},{"name" : "Knowledge (Technology)", "ability" : "(Int)"}, {"name" : "Perception", "ability" : "(Wis)"},{"name" : "Persuasion", "ability" : "(Cha)"},{"name" : "Pilot", "ability" : "(Dex)"},{"name" : "Ride", "ability" : "(Dex)"},{"name" : "Treat Injury", "ability" : "(Wis)"},{"name" :  "Use Computer", "ability" : "(Int)"}
  ],
    "Scoundrel" : [{"name" : "Acrobatics", "ability" : "(Dex)"},{"name" : "Deception", "ability" : "(Cha)"},{"name" : "Gather Information", "ability" : "(Cha)"}, {"name" : "Initiative", "ability" : "(Dex)"} ,{"name" : "Knowledge (Bureaucracy)", "ability" : "(Int)"}, {"name" : "Knowledge (Galactic Lore)", "ability" : "(Int)"},{"name" : "Knowledge (Life Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Physical Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Social Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Tactics)", "ability" : "(Int)"},{"name" : "Knowledge (Technology)", "ability" : "(Int)"}, {"name" : "Mechanics", "ability" : "(Int)"},{"name" : "Perception", "ability" : "(Wis)"},{"name" : "Persuasion", "ability" : "(Cha)"},{"name" : "Pilot", "ability" : "(Dex)"},{"name" : "Stealth", "ability" : "(Dex)"},{"name" :  "Use Computer", "ability" : "(Int)"}
  ],
    "Scout" : [{"name" : "Climb", "ability" : "(Str)"}, {"name" : "Endurance", "ability" : "(Con)"}, {"name" : "Initiative", "ability" : "(Dex)"}, {"name" : "Jump", "ability" : "(Str)"}, {"name" : "Knowledge (Bureaucracy)", "ability" : "(Int)"}, {"name" : "Knowledge (Galactic Lore)", "ability" : "(Int)"},{"name" : "Knowledge (Life Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Physical Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Social Sciences)", "ability" : "(Int)"} ,{"name" : "Knowledge (Tactics)", "ability" : "(Int)"},{"name" : "Knowledge (Technology)", "ability" : "(Int)"},{"name" : "Mechanics", "ability" : "(Int)"},{"name" : "Perception", "ability" : "(Wis)"} ,{"name" : "Pilot", "ability" : "(Dex)"},{"name" : "Ride", "ability" : "(Dex)"},{"name" : "Stealth", "ability" : "(Dex)"}, {"name" : "Survival", "ability" : "(Wis)"},{"name" : "Swim", "ability" : "(Str)"}
  ],
    "Soldier" : [{"name" : "Climb", "ability" : "(Str)"},{"name" : "Endurance", "ability" : "(Con)"}, {"name" : "Initiative", "ability" : "(Dex)"},{"name" : "Jump", "ability" : "(Str)"},{"name" : "Knowledge (Tactics)", "ability" : "(Int)"} ,{"name" : "Mechanics", "ability" : "(Int)"},{"name" : "Perception", "ability" : "(Wis)"},{"name" : "Pilot", "ability" : "(Dex)"},{"name" : "Swim", "ability" : "(Str)"},{"name" : "Treat Injury", "ability" : "(Wis)"},{"name" : "Use Computer", "ability" : "(Int)"}
  ]
};

export const prestigeSkills = {};



